### ISSUE TITLE
make ARCH=arm failed

### ISSUE THREAD

**Issue by JoeyJiao** [linuxep/lepd#13]
linuxep/lepd/libs/libsysstat.a: error adding symbols: Archive has no index; run ranlib to add one
collect2: error: ld returned 1 exit status
Makefile:65: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by linuxep** [comment]
are you using right toolchain? we don't have this problem.

**Comment by JoeyJiao** [comment]
Which one are you using? I'm working on ubuntu 16.04 LTS, gcc-arm-linux-gnueabi is installed from apt

**Comment by JoeyJiao** [comment]
OK, find it out, gcc5 not working while gcc-4.9 works

**Comment by 21cnbao** [comment]
can you tell the compile log of gcc5?

**Comment by JoeyJiao** [comment]
Not an issue, make clean before run make ARCH=arm
